services:
  - type: web
    name: mastermind-gadgets
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: your-pre-generated-app-key
      - key: APP_URL
        value: https://mastermind-gadgets.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
