services:
  - type: web
    name: mastermind-gadgets
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:qYkNUZeUYfoyo/GcIaarhOcFrgcy6Y5jwjt+IfF64lE=
      - key: APP_URL
        value: https://mastermind-gadgets.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-east-2.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: your-actual-password
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
